name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Sync files to S3
        run: aws s3 sync . s3://www.jishrami.com --delete
