name: Assume IAM Role

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-west-2"
  BUCKET_NAME: "www.jishrami.com"

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Sync S3
        run: |
          aws s3 sync . s3://${BUCKET_NAME} --exclude ".git/*" --exclude ".github/*" --delete

      - name: Invalidate CloudFront Cache for www.jishrami.com
        run: |
          for dist_id in ${{ secrets.CF_DIST_ID }} ${{ secrets.CF_DIST_ID2 }}; do
            aws cloudfront create-invalidation --distribution-id ${dist_id} --paths "/*"
          done

      - name: Verify IAM Role
        run: |
          aws sts get-caller-identity
